version: '3'

services:
  traefik:
    image: traefik:rocamadour
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/traefik:/etc/traefik
      - /etc/certs/motint.xyz:/etc/certs/motint.xyz 
    networks:
      - internal

  prometheus:
    image: prom/prometheus:v2.15.2
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - /opt/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - "--web.route-prefix=/"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - internal
    depends_on:
      - traefik

  grafana:
    image: grafana/grafana:6.6.1
    restart: unless-stopped
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
      - /opt/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - /opt/reverse-proxy_rev1.json:/etc/grafana/provisioning/dashboards/reverse-proxy_rev1.json
      - /opt/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_PROXY_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - internal

networks:
  internal:

volumes:
  prometheus:
  grafana: